const API_BASE = "/api";
const SESSION_KEY = "gvx_customer_session";
const LICENSE_KEY = "gvx_customer_license";
const REFRESH_MS = 5000;
let session = localStorage.getItem(SESSION_KEY) || "";
let licenseKey = localStorage.getItem(LICENSE_KEY) || "";
const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(v,currency="USD"){const n=Number(v||0);return `${n<0?'-':''}${Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}`}
function date(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'}).format(d)}
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(session)headers.Authorization=`Bearer ${session}`;const r=await fetch(API_BASE+path,{...opt,headers,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(r.status===401){localStorage.removeItem(SESSION_KEY);localStorage.removeItem(LICENSE_KEY);location.href='customer_login.html';throw new Error('SESSION_EXPIRED')}if(!r.ok||d.success===false)throw new Error(d.error||`HTTP_${r.status}`);return d}
function render(data){const l=data.license||{},m=data.monitor||{};const positions=data.positions||[];const currency=m.currency||'USD';const online=String(m.ea_status||'').toUpperCase().includes('ONLINE')&&m.last_update&&((Date.now()-new Date(m.last_update).getTime())<10*60*1000);if($('userName'))$('userName').textContent=data.user?.name||'Customer';if($('accountLogin'))$('accountLogin').textContent=m.mt5_account||l.mt5_account||'Waiting for MT5 data...';if($('accountId'))$('accountId').textContent=m.mt5_account||l.mt5_account||'—';if($('server'))$('server').textContent=m.server||m.broker||'—';if($('monitorStatus'))$('monitorStatus').textContent=online?'ONLINE':'OFFLINE';if($('lastUpdate'))$('lastUpdate').textContent=date(m.last_update);if($('balance'))$('balance').textContent=money(m.balance,currency);if($('equity'))$('equity').textContent=money(m.equity,currency);if($('profit'))$('profit').textContent=money(m.floating_profit,currency);if($('swap'))$('swap').textContent=money(m.swap,currency);if($('margin'))$('margin').textContent=money(m.margin,currency);if($('freeMargin'))$('freeMargin').textContent=money(m.free_margin,currency);if($('marginLevel'))$('marginLevel').textContent=`${Number(m.margin_level||0).toLocaleString('en-US',{maximumFractionDigits:2})}%`;if($('licenseStatus'))$('licenseStatus').textContent=l.status||'—';if($('licenseBadge'))$('licenseBadge').textContent=l.status||'—';if($('licenseKey'))$('licenseKey').textContent=l.license_key||licenseKey||'—';if($('expiresAt'))$('expiresAt').textContent=date(l.expires_at);if($('remaining')){const days=l.expires_at?Math.max(0,Math.ceil((new Date(l.expires_at)-Date.now())/86400000)):0;$('remaining').textContent=`${days} day${days===1?'':'s'}`}if($('positionCount'))$('positionCount').textContent=`${positions.length} POSITION${positions.length===1?'':'S'}`;if($('positionsBody'))$('positionsBody').innerHTML=positions.length?positions.map(p=>`<tr><td>${esc(p.symbol)}</td><td>${esc(p.position_type)}</td><td>${esc(p.volume)}</td><td>${esc(p.open_price)}</td><td>${esc(p.current_price)}</td><td>${esc(p.sl)}</td><td>${esc(p.tp)}</td><td>${esc(p.profit)}</td></tr>`).join(''):`<tr><td colspan="8">No open positions.</td></tr>`;if($('systemMessage'))$('systemMessage').textContent=online?'Monitor EA is connected and dashboard is receiving MT5 data.':'Monitor EA is offline or has not sent a recent heartbeat.'}
async function load(){try{const me=await api('/me');if(me.user?.role!=='CUSTOMER')throw new Error('CUSTOMER_ACCESS_REQUIRED');if(!licenseKey){const ml=await api('/my-license');licenseKey=ml.license?.license_key||ml.licenses?.[0]?.license_key||'';if(licenseKey)localStorage.setItem(LICENSE_KEY,licenseKey)}if(!licenseKey)throw new Error('LICENSE_NOT_ASSIGNED');const data=await api('/dashboard?license_key='+encodeURIComponent(licenseKey));render(data);try{const mt=await api('/my-monitor-token');if($('monitorToken'))$('monitorToken').value=mt.monitor?.monitor_token||''}catch{}}catch(e){if($('systemMessage'))$('systemMessage').textContent=e.message}}
$('logoutBtn')?.addEventListener('click',async()=>{try{await api('/logout',{method:'POST'})}catch{}localStorage.removeItem(SESSION_KEY);localStorage.removeItem(LICENSE_KEY);location.href='customer_login.html'});
$('resendLicense')?.addEventListener('click',async()=>{try{await api('/resend-license',{method:'POST',body:JSON.stringify({license_key:licenseKey})});alert('License email resent.')}catch(e){alert(e.message)}});
$('copyMonitorToken')?.addEventListener('click',async()=>{const v=$('monitorToken')?.value;if(v){await navigator.clipboard.writeText(v);$('copyMonitorToken').textContent='COPIED';setTimeout(()=>$('copyMonitorToken').textContent='COPY',1200)}});
(async()=>{if(!session){location.href='customer_login.html';return}await load();setInterval(load,REFRESH_MS)})();
