const API_BASE="/api",SESSION_KEY="gvx_admin_session";
let session=localStorage.getItem(SESSION_KEY)||"",users=[],licenses=[],selectedCustomer=null,revealedPassword="";
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>{if(!v||v==='—')return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'}).format(d)};
const headers=()=>{const h={'Content-Type':'application/json','Accept':'application/json'};if(session)h.Authorization=`Bearer ${session}`;return h};
async function api(path,opt={}){const r=await fetch(API_BASE+(path.startsWith('/')?path:`/${path}`),{...opt,headers:{...headers(),...(opt.headers||{})},cache:'no-store'});const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch(_){if(r.status===401){localStorage.removeItem(SESSION_KEY);location.href='login.html'}throw new Error(raw?`API returned non-JSON response (HTTP ${r.status})`:`API returned an empty response (HTTP ${r.status})`)}if(r.status===401){localStorage.removeItem(SESSION_KEY);location.href='login.html';throw new Error('SESSION_EXPIRED')}if(!r.ok||d.success===false)throw new Error(d.error||d.message||`HTTP_${r.status}`);return d}
function status(s){const v=String(s||'UNKNOWN'),u=v.toUpperCase(),c=u.includes('EXPIRE')?'expired':u.includes('ACTIVE')?'active':'pending';return `<span class="status ${c}"><span class="dot"></span>${esc(v)}</span>`}
function normalize(x){const l=x.license||x.licenses?.[0]||{};return{raw:x,name:x.name||x.full_name||x.customer_name||'—',email:x.email||'—',mt5_account:x.mt5_account||l.mt5_account||'—',server:x.server||l.server||'—',broker:x.broker||l.broker||'—',symbol:x.symbol||l.symbol||'—',trading_days:x.trading_days??x.maximum_trading_days??l.trading_days??l.maximum_trading_days??'—',activated_at:x.activated_at||l.activated_at,expires_at:x.expires_at||l.expires_at,license_key:x.license_key||l.license_key||'—',license_status:x.license_status||x.status||l.license_status||l.status||'—',created_at:x.created_at||l.created_at,updated_at:x.updated_at||l.updated_at}}
function renderStats(){const el=$('stats');if(!el)return;const a=users.filter(x=>String(x.license_status).toUpperCase().includes('ACTIVE')).length,e=users.filter(x=>String(x.license_status).toUpperCase().includes('EXPIRE')).length;el.innerHTML=`<div class="stat"><div class="label">TOTAL RECORDS</div><div class="value">${users.length}</div></div><div class="stat"><div class="label">ACTIVE</div><div class="value">${a}</div></div><div class="stat"><div class="label">EXPIRED</div><div class="value">${e}</div></div><div class="stat"><div class="label">WITH LICENSE</div><div class="value">${users.filter(x=>x.license_key!=='—').length}</div></div>`}
function renderUsers(){const table=$('tableWrap');if(!table)return;const q=($('searchBox')?.value||'').toLowerCase(),rows=users.filter(x=>!q||[x.name,x.email,x.mt5_account,x.server,x.broker,x.license_key,x.license_status].join(' ').toLowerCase().includes(q));table.innerHTML=rows.length?`<table class="table"><thead><tr><th>CUSTOMER</th><th>MT5 ACCOUNT</th><th>SERVER</th><th>LICENSE</th><th>ACTIVATED</th><th>EXPIRES</th><th>STATUS</th><th></th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td><strong>${esc(x.name)}</strong><br><span class="muted small">${esc(x.email)}</span></td><td>${esc(x.mt5_account)}</td><td>${esc(x.server)}</td><td>${esc(x.license_key)}</td><td>${esc(fmt(x.activated_at))}</td><td>${esc(fmt(x.expires_at))}</td><td>${status(x.license_status)}</td><td><button class="viewbtn" data-view="${i}">VIEW</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No activation records found.</div>';table.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openDetail(rows[+b.dataset.view]))}
function resetCredential(){selectedCustomer=null;revealedPassword='';if($('passwordMask'))$('passwordMask').textContent='••••••••••••';if($('revealPasswordBtn')){ $('revealPasswordBtn').disabled=false;$('revealPasswordBtn').textContent='REVEAL'; }if($('copyPasswordBtn'))$('copyPasswordBtn').disabled=true;if($('credentialMessage'))$('credentialMessage').textContent='Password is hidden by default. Click REVEAL to retrieve it securely.';const state=document.querySelector('.credential-state');if(state)state.textContent='HIDDEN'}
function openDetail(x){const card=$('detailCard');selectedCustomer=x;resetCredential();selectedCustomer=x;if(!card){alert(`Activation Details\n\nCustomer: ${x.name}\nEmail: ${x.email}\nMT5 Account: ${x.mt5_account}\nServer: ${x.server}\nBroker: ${x.broker}\nSymbol: ${x.symbol}\nLicense: ${x.license_key}\nStatus: ${x.license_status}\nActivated: ${fmt(x.activated_at)}\nExpires: ${fmt(x.expires_at)}`);return}card.classList.remove('hidden');$('detailTitle').textContent=x.name;$('detailGrid').innerHTML=[['Full Name',x.name],['Email',x.email],['MT5 Account ID',x.mt5_account],['Server',x.server],['Broker',x.broker],['Symbol',x.symbol],['Maximum Trading Days',x.trading_days],['Activation Date (WIB)',fmt(x.activated_at)],['Expiry Date (WIB)',fmt(x.expires_at)],['License Key',x.license_key],['License Status',status(x.license_status)],['Created At (WIB)',fmt(x.created_at)],['Updated At (WIB)',fmt(x.updated_at)]].map(([k,v])=>`<div class="detail-item"><div class="k">${esc(k)}</div><div class="v">${k==='License Status'?v:esc(v)}</div></div>`).join('');card.scrollIntoView({behavior:'smooth',block:'start'})}
async function revealPassword(){if(!selectedCustomer)return;const btn=$('revealPasswordBtn'),msg=$('credentialMessage'),mask=$('passwordMask'),state=document.querySelector('.credential-state');btn.disabled=true;btn.textContent='LOADING...';msg.textContent='Retrieving encrypted MT5 credential securely...';try{const key=selectedCustomer.license_key,account=selectedCustomer.mt5_account;let d=null;if(key&&key!=='—')d=await api('/admin/credentials?license_key='+encodeURIComponent(key));else if(account&&account!=='—')d=await api('/admin/credentials?mt5_account='+encodeURIComponent(account));else throw new Error('MT5_ACCOUNT_OR_LICENSE_REQUIRED');if(!d.credential_available||!d.credentials?.mt5_password)throw new Error(d.error||d.message||'MT5_CREDENTIAL_NOT_FOUND');revealedPassword=String(d.credentials.mt5_password);mask.textContent=revealedPassword;btn.textContent='HIDE';btn.disabled=false;if($('copyPasswordBtn'))$('copyPasswordBtn').disabled=false;if(state)state.textContent='VISIBLE';msg.textContent='MT5 password retrieved securely. Click HIDE to conceal it again.';btn.onclick=hidePassword}catch(e){btn.disabled=false;btn.textContent='REVEAL';msg.textContent=e.message||'Unable to retrieve MT5 password.';msg.className='small error'}}
function hidePassword(){revealedPassword='';if($('passwordMask'))$('passwordMask').textContent='••••••••••••';if($('copyPasswordBtn'))$('copyPasswordBtn').disabled=true;const btn=$('revealPasswordBtn');if(btn){btn.textContent='REVEAL';btn.disabled=false;btn.onclick=revealPassword}const state=document.querySelector('.credential-state');if(state)state.textContent='HIDDEN';if($('credentialMessage')){$('credentialMessage').textContent='Password is hidden by default. Click REVEAL to retrieve it securely.';$('credentialMessage').className='small muted'}}
async function copyPassword(){if(!revealedPassword)return;try{await navigator.clipboard.writeText(revealedPassword);$('credentialMessage').textContent='MT5 password copied to clipboard.'}catch(_){$('credentialMessage').textContent='Copy failed. Please select and copy the password manually.'}}
function renderLicenses(){const el=$('licenseWrap');if(!el)return;el.innerHTML=licenses.length?`<table class="table"><thead><tr><th>LICENSE</th><th>MT5</th><th>CUSTOMER</th><th>ACTIVATED</th><th>EXPIRES</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>${licenses.map(x=>{const a=String(x.status||x.license_status).toUpperCase()==='ACTIVE';return`<tr><td>${esc(x.license_key)}</td><td>${esc(x.mt5_account||'—')}</td><td>${esc(x.customer_email||x.email||'Unassigned')}</td><td>${esc(fmt(x.activated_at))}</td><td>${esc(fmt(x.expires_at))}</td><td>${status(x.license_status||x.status)}</td><td><button class="viewbtn" data-key="${esc(x.license_key)}" data-next="${a?'SUSPENDED':'ACTIVE'}">${a?'SUSPEND':'ACTIVATE'}</button></td></tr>`}).join('')}</tbody></table>`:'<div class="empty">No licenses found.</div>';el.querySelectorAll('[data-key]').forEach(b=>b.onclick=async()=>{try{await api('/admin/update-license',{method:'POST',body:JSON.stringify({license_key:b.dataset.key,status:b.dataset.next})});await loadAll()}catch(e){alert(e.message)}})}
function renderQueue(rows){const el=$('queueWrap');if(!el)return;el.innerHTML=rows.length?`<table class="table"><thead><tr><th>CUSTOMER</th><th>LICENSE</th><th>MT5</th><th>BROKER</th><th>CREATED</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}<br><span class="muted small">${esc(x.email)}</span></td><td>${esc(x.license_key)}</td><td>${esc(x.mt5_account||'—')}</td><td>${esc(x.broker||'—')}</td><td>${esc(fmt(x.created_at))}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Queue is empty.</div>'}
async function loadAll(){try{const[u,l,q]=await Promise.all([api('/admin/users'),api('/admin/licenses'),api('/admin/activation-queue')]);users=(u.users||u.customers||u.data||[]).map(normalize);licenses=l.licenses||[];renderStats();renderUsers();renderLicenses();renderQueue(q.queue||[])}catch(e){const el=$('tableWrap');if(el)el.innerHTML=`<div class="empty error">${esc(e.message)}</div>`}}
$('searchBox')?.addEventListener('input',renderUsers);$('refreshBtn')?.addEventListener('click',loadAll);$('closeDetail')?.addEventListener('click',()=>$('detailCard')?.classList.add('hidden'));$('revealPasswordBtn')?.addEventListener('click',revealPassword);$('copyPasswordBtn')?.addEventListener('click',copyPassword);$('logoutBtn')?.addEventListener('click',()=>{localStorage.removeItem(SESSION_KEY);localStorage.removeItem('gvx_admin_user');location.href='login.html'});$('createLicenseBtn')?.addEventListener('click',async()=>{const mt5=prompt('MT5 Account ID (optional):','')??'',broker=prompt('Broker / Server (optional):','')??'',days=prompt('Trading days:','30');if(days===null)return;try{const d=await api('/admin/create-license',{method:'POST',body:JSON.stringify({mt5_account:mt5,broker,trading_days:Number(days)})});alert('License created: '+d.license.license_key);await loadAll()}catch(e){alert(e.message)}});
(async()=>{if(!session){location.href='login.html';return}try{const me=await api('/me');if(me.user?.role!=='ADMIN')throw new Error('ADMIN_ACCESS_REQUIRED');if($('adminName'))$('adminName').textContent=me.user.name||'Administrator';await loadAll()}catch(e){localStorage.removeItem(SESSION_KEY);location.href='login.html'}})();
